### ISSUE TITLE
use <script async> or or createElement('script'); in http://pypyjs.org/

### ISSUE THREAD

**Issue by xcombelle** [rfk/pypyjs#101]
By watching the firefox console, the following make me think a little.

     Successfully compiled asm.js code (total compilation time 7739ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'); 4 functions compiled slowly: HMc:7:115040 (253ms), zEa:7:531093 (396ms), QGc:7:1472335 (294ms), mFa:17:9 (414ms))

Maybe it would be possible to use the proposed solution.

**Comment by rfk** [comment]
Yep; see https://github.com/rfk/pypyjs/issues/24 and https://github.com/rfk/pypyjs/pull/47 for my first attempt at this, which will be included in the next release.  It doesn't seem to cache the bytecode properly though, so I'll continue to investigate.

**Comment by rfk** [comment]
The caching seems to be working in Firefox Nightly, so I guess it's just buggy in release firefox.  Closing this for now, but feel free to re-open if the upcoming 0.3.0 version doesn't seem to cache properly for you.
