### ISSUE TITLE
vm.exec().failed(...) ?

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#105]
Is there a callback mechanism if a ```vm.exec()``` call is failed?!?

This would be helpful for selenium tests ( https://github.com/rfk/pypyjs/pull/96 ) to have a faster break after execution failed... Currently the timeout must be must be reached...

**Comment by jedie** [comment]
OK, i find out that i can use ```vm.exec("...").then(func_ok, func_failed);```

**Comment by rfk** [comment]
You can also use `.catch(func_failed)` which is part of the upcoming `Promise` API standard: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch
