### ISSUE TITLE
Reduce overhead of creating multiple PyPyJS instances

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#106]
Is there a way to reset the VM ?

This would be helpful for fast, atomic selenium unitests...

**Comment by rfk** [comment]
Not easily.  We could fake it by clearing the scope that code runs in, but that wouldn't help for modules that have global state.

A better option would be to create a fresh VM for every test with `new PyPyJS()` but this is currently very expensive, as it loads and parses `pypy.vm.js` each time.  So I think the best way forward may be to refactor the constructor so you can call `new PyPyJS()` multiple times without so much overhead.

**Comment by jedie** [comment]
> So I think the best way forward may be to refactor the constructor so you can call new PyPyJS() multiple times without so much overhead.
:+1:

**Comment by rfk** [comment]
This should be somewhat improved by https://github.com/rfk/pypyjs/commit/2ca8fdc1c332eb666f1073d11410c99d683bac6d, although I'm sure there's still more overhead that we could get rid of.

**Comment by jedie** [comment]
Great!

I use this in https://github.com/jedie/pypyjs/commit/b01b7517b6135fa942a0c502d4dbc06993b85631 and commit also a unittest for it.
