### ISSUE TITLE
not all functions from 'gc' module worked...

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#114]
```
import gc

print "garbage collection enabled:", gc.isenabled()
print "gc.garbage:", gc.garbage
print gc.set_stats(gc.DEBUG_LEAK)
print gc.get_count()
print gc.get_stats()
```
**gc.isenabled()** and **gc.garbage** worked. Other methods result in: **AttributeError: 'module' object has no attribute 'foobar'**

Maybe a limitation of pypy?!?

**Comment by rfk** [comment]
I get the same behaviour in a native pypy shell; the pypy docs also give a general warning that "some functions and attributes of the gc module behave in a slightly different way":

  http://pypy.readthedocs.org/en/latest/cpython_differences.html

So I don't think there's much we can do about this one sadly.

**Comment by jedie** [comment]
Ah, ok. Then there is nothing to do here ;)
Thanks for the information.
