### ISSUE TITLE
non-jit build?

### ISSUE THREAD

**Issue by perkinslr** [rfk/pypyjs#123]
Would it be possible to get a non-jit pypy.vm.js somewhere in git?  I've got a function call that is running slower with each consecutive call and I'm curious if it's something with the JIT or something else.

**Comment by jedie** [comment]
Not in git, but downloadable: https://github.com/rfk/pypyjs/releases/download/v0.3.0/pypy-nojit.js-0.3.0.tar.gz

**Comment by perkinslr** [comment]
Thanks, didn't even think to look outside the website folder.

**Comment by rfk** [comment]
> didn't even think to look outside the website folder.

That download is new as of yesterday, and built at your suggestion :-)
I finally got around to tagging something as v0.3.0, but forgot to cycle back and update you in this bug...

**Comment by perkinslr** [comment]
Ah, okay, no worries, and thanks for the build!
