### ISSUE TITLE
<js.String 'BaseHTTPServer'> -> TypeError: obj is undefined

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#124]
```#!python
import js

modules = js.globals.vm._allModules
print modules
print dir(modules)

print modules[0]
print dir(modules[0])
```
output:
```
[object Object]
[<js.String 'BaseHTTPServer'>, <js.String 'Bastion'>, ..., <js.String 'xmlrpclib'>, <js.String 'zipfile'>]
undefined
Traceback (most recent call last):
  File "c callback", line 8, in <module>
  File "<string>", line 7, in <module>
Error: TypeError: obj is undefined
```

Where is my mistake?

**Comment by rfk** [comment]
That's a legitimate javascript error, doing `undefined[0]` in JS will give the same thing.  The `_allModules` is a dict, not a list:
```
modules = js.globals.vm._allModules
print modules['BaseHTTPServer']
```

**Comment by jedie** [comment]
Hm. But not a real python dict, isn't it?
```
modules = js.globals.vm._allModules
print repr(modules) # -> <js.Object handle=9>
```
Using **modules.keys()** or **modules.items()** doesn't work.
**dir(modules)** returns the list: ```[<js.String 'BaseHTTPServer'>, <js.String 'Bastion'>, ...```

solution for the initial problem:
```
modules = js.globals.vm._allModules  
module_names = [str(m) for m in modules]
print module_names
```
will print:
```
['BaseHTTPServer', 'Bastion', 'CGIHTTPServer', 'ConfigParser', 'Cookie',...]
```

btw:
```
len(js.globals.vm._allModules) -> TypeError: 'Object' has no length
```

**Comment by rfk** [comment]
> But not a real python dict, isn't it?

Correct; I should have said "javascript hash object", technically an instance of `js.Object` which is dict-like but doesn't implement all the methods of standard python dictionaries.

**Comment by rfk** [comment]
> len(js.globals.vm._allModules) -> TypeError: 'Object' has no length

Unfortunately this is the expected behavior, there's no easy way to tell the number of keys in a javascript hash object.

**Comment by jedie** [comment]
Thanks for the information... Now i have commit with https://github.com/jedie/pypyjs/commit/53cbf2a651817cdadcb8143175fca1d6c2a31e5a a fast, complete import test... ;)
