### ISSUE TITLE
from test import pystone stopped working.

### ISSUE THREAD

**Issue by albertjan** [rfk/pypyjs#131]
```py
Welcome to PyPy.js!
>>> from test import pystone
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named test
```

**Comment by rfk** [comment]
Whoops!  The code to make this work got lost in a refactor; restored in https://github.com/rfk/pypyjs/commit/3eab125b9e16d5b726c6177c42c911ce6d933efb and I'll push an update to the website shortly.

Thanks for the report!

**Comment by albertjan** [comment]
wow thats quick thanks :smile:
