### ISSUE TITLE
Encoding functions are broken

### ISSUE THREAD

**Issue by ArrestedDevelopment** [rfk/pypyjs#30]
For example, if you try to import the `json` module, you get this error:

```
>>> import json
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/pypyjs/lib_pypy/json/__init__.py", line 114, in <module>
    from .decoder import JSONDecoder
  File "/lib/pypyjs/lib_pypy/json/decoder.py", line 24, in <module>
    NaN, PosInf, NegInf = _floatconstants()
  File "/lib/pypyjs/lib_pypy/json/decoder.py", line 18, in _floatconstants
    _BYTES = '7FF80000000000007FF0000000000000'.decode('hex')
LookupError: unknown encoding: hex
```

I also run into it when using the module `rcssmin`, which has this for its `__author__`:

````python
__author__ = "Andr\xe9 Malo"
__author__ = getattr(__author__, 'decode', lambda x: __author__)('latin-1')
```

Which outputs this error:

```
debug: OperationError:
debug:  operror-type: LookupError
debug:  operror-value: unknown encoding: latin-1
```

And if I try to import the module `markupsafe`, I get this bizarre error:

```
>>> import markupsafe
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/pypyjs/lib_pypy/markupsafe/__init__.py", line 30
    The `escape` function returns markup objects so that double escaping can't
                                                                            ^
SyntaxError: EOL while scanning string literal
```

[link to the code for convenience](https://github.com/mitsuhiko/markupsafe/blob/b18391aad21f6ce3b2f21644ecd1b1a976375713/markupsafe/__init__.py#L32)

These weird errors in the multiline comments will go away if I take the `# -*- coding: utf-8 -*-` encoding comment out of the top of the files in the module

**Comment by rfk** [comment]
Thanks for digging into this.  It seems to work if you explicitly load the "hex" codec beforehand:
```
>>> import encodings.hex_codec
>>> import json
```
So this is almost certainly due to some side-effect of the odd way we initialize the set of importable modules.

**Comment by rfk** [comment]
A simple fix may be to include `encodings/*` in the default set of eagerly-loaded modules.  It's a lot of code to load up-front but may be necessary.

**Comment by rfk** [comment]
In https://github.com/rfk/pypyjs/commit/bb883d33a96aa7b8792e116b91b87616270a737e I added some common encodings to the preloaded module set.  It seems to help for at least `import json`.

**Comment by rfk** [comment]
And look at the diff, it's pretty obvious I'm messing up the encoding declaration on these files, will push a fix for that shortly...

**Comment by rfk** [comment]
OK https://github.com/rfk/pypyjs/commit/a7726e5c51cc515a36f0d6e83e2ca7bd4548102c should fix the problem with missing linebreaks after the encoding headers.  Let me know if this works for you.

**Comment by ArrestedDevelopment** [comment]
Sadly that didn't work; it'll only work if I use `--preload=encodings.hex_codec` when bundling everything with module_bundler.py.

And for some reason, packing the encodings doesn't work for files with the encoding comment at the top, this example from webencodings:

```
>>> import webencodings
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/pypyjs/lib_pypy/webencodings/__init__.py", line 62
    This is the specs `get an encoding
                    ^
SyntaxError: Unknown character
```

The character it hates being:

        This is the spec’s `get an encoding

The apostrophe in "spec’s"

I even went insane and preloaded all of the encoding modules, I threw the [flags on pastebin](http://pastebin.com/N218WUXY) if anyone wants it.

**Comment by rfk** [comment]
Huh, I just noticed that my claimed fix in bb883d3 didn't actually caused the encodings to be pre-loaded.  Not sure what happened there!  I committed 7ac46afc9c017a78df36e223caffbbf31df3e1a0 which should *actually* pre-load them by default.

**Comment by rfk** [comment]
AFAICT this is working now, thanks again for the report.

**Comment by ArrestedDevelopment** [comment]
I just tried it out, and it works great! thank you!
