### ISSUE TITLE
Support serializing python dicts to javascript objects

### ISSUE THREAD

**Issue by asottile** [rfk/pypyjs#35]
```
>>> js.globals['JSON'].stringify({'foo': 'bar'})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: could not convert py type to js type
```

Expected:

```
>>> js.globals['JSON'].stringify({'foo': 'bar'})
<js.String '{"foo":"bar"}'>
```

**Comment by tritium21** [comment]
but...they pythonic way of doing that, which is the point of this entire exorcise IIUC, is to use the python json module.

**Comment by asottile** [comment]
Oh for sure. The stringify method is the simplest global to demonstrate a round trip.  Either way i almost have a patch ready

**Comment by rfk** [comment]
This landed and will be in the next release
