### ISSUE TITLE
sys.platform returns 'linux2'

### ISSUE THREAD

**Issue by bcj** [rfk/pypyjs#49]
I'm not sure what the most appropriate platform would be. I'd say 'web', but if this is running on top of node/io then that isn't exactly true. 'javascript'?

**Comment by crantila** [comment]
This would be super handy for patching modules that expect some of the blacklisted modules to be available.

**Comment by rfk** [comment]
https://github.com/rfk/pypyjs/commit/ca2608d6f227b65f60fe3259f976396b25303681 adds a bit of a hack to set `sys.platform == "js"`; hopefully it's enough to fool most things.

**Comment by jedie** [comment]
Now it's back to "linux2", isn't it?

**Comment by rfk** [comment]
I've pushed an updated build in the `website` dir so this should work from master now.
