### ISSUE TITLE
js.eval doesn't assign at the global scope

### ISSUE THREAD

**Issue by bcj** [rfk/pypyjs#56]
To reproduce: 
```
>>>import js
>>>js.eval('var one = 1')
>>>js.eval('one')
Error: ReferenceError: one is not defined
```

The same occurs with function definitions.

**Comment by rfk** [comment]
If you want to dig into this, the underlying implementation of `js.eval` is in deps/pypy/rpython/translator/platform/emscripten_platform/library_emjs.js.  It just calls through to the js native `eval()` call though so I'm not sure why the behaviour is different.

**Comment by arcanis** [comment]
I think you should use `window.eval` instead of `eval`. Otherwise, the eval is scopped inside the caller.

Check out this [jsfiddle](http://jsfiddle.net/23poq10m/) for an example.

**Comment by rfk** [comment]
Thanks for the tip @arcanis.  The precise scoping rules seem terrifyingly brittle to me, per description in http://perfectionkills.com/global-eval-what-are-the-options/

I'm going to attempt to force `js.eval` to execute at global scope, which should better match user expectations.  But it might be a little fragile

**Comment by rfk** [comment]
Hopefully fixed by https://github.com/rfk/pypy/commit/010ad04a21b64afcb7745e3e878d2a2ec5f6c1c8
