### ISSUE TITLE
"Startup on This Machine" on http://arewepythonyet.com/startup.html doesn't work

### ISSUE THREAD

**Issue by gavinwahl** [rfk/pypyjs#66]
When I click "Click to Test Now", I get "Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://pypyjs.org/demo/lib/pypy.js' failed to load."

<http://pypyjs.org/demo/lib/pypy.js> is a 404.

**Comment by rfk** [comment]
Whoops, thanks, should be fixed by https://github.com/rfk/arewepythonyet/commit/9bce233761dd977a8a3a063b6dad3a0eea5f447b
