### ISSUE TITLE
Getting OperationError on import with latest master

### ISSUE THREAD

**Issue by asottile** [rfk/pypyjs#68]
```
>>> from test import pystone
debug: OperationError:
debug:  operror-type: SyntaxError
debug:  operror-value: ('EOL while scanning string literal', ('c callback', 1, 12, "r = c.push('\n", 0))
debug: OperationError:
debug:  operror-type: KeyError
debug:  operror-value: 'r'
```

**Comment by asottile** [comment]
Actually it seems to be any command I run (even just pressing [enter])

**Comment by asottile** [comment]
Seems broken on http://pypyjs.org/ as well

**Comment by asottile** [comment]
Seems to be browser / version related.  I'm running firefox 37.0.1 on ubuntu 14.04.  It seems to work in chrome 41

Seems to also work in 36.0.4 on OSX

**Comment by asottile** [comment]
wacky, I restarted my machine and the problem fixed itself O_o

**Comment by rfk** [comment]
I occasionally see weird behaviour due to caching issues, which can cause the `vm.mem.js` from one compile to be used with the `.vm.js` from a different compile.  Possible you hit something similar?

**Comment by asottile** [comment]
Probably, I found it a bit odd that restarting the browser made no difference and that I had to restart my entire machine.  Ah well!
