### ISSUE TITLE
module_bundler.py needs a "remove" command

### ISSUE THREAD

**Issue by crantila** [rfk/pypyjs#74]
After we add a module, the only way to remove it is by starting over from scratch. I'm sure someone's already thought of this and just hasn't had the time to implement it yet.

**Comment by rfk** [comment]
Indeed, thanks for mentioning this, I've had it in the back of my mind but never got around to writing it down.  A related piece of functionality is the ability to "un-preload" a module that was previously put in the preload data set.

**Comment by perkinslr** [comment]
The un-preload I think is more important than the remove, but I'm not certain how to implement it.  Next time I've got the code open I'll see if I can add remove, since it should be very similar to blacklist.

**Comment by rfk** [comment]
IIUC this is now implemented thanks to @perkinslr
