### ISSUE TITLE
module_bundler.py fails if path contains accented letters

### ISSUE THREAD

**Issue by MaximeCheramy** [rfk/pypyjs#75]
```
Traceback (most recent call last):
  File "../../tools/module_bundler.py", line 650, in <module>
    res = main(sys.argv)
  File "../../tools/module_bundler.py", line 190, in main
    cmd_add(bundler, opts)
  File "../../tools/module_bundler.py", line 236, in cmd_add
    bundler.flush_index()
  File "../../tools/module_bundler.py", line 332, in flush_index
    filepath = os.path.join(self.bundle_dir, moddata["file"])
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

Here, self.bundle_dir is: `/home/max/Téléchargements/pypy.js-0.2.0/lib/modules`

**Comment by perkinslr** [comment]
What version of python are you using for module_bundler?  And what's your system (and python's) encoding?  I'm having a hard time reproducing this error, so there has to be something encoding-related different between your machine and mine.

**Comment by MaximeCheramy** [comment]
I have this error with Python 2.7.8 on Debian Jessie:

    Python 2.7.8 (default, Oct  7 2014, 17:59:21) 
    [GCC 4.9.1] on linux2

Same issue with PyPy:

    Python 2.7.8 (2.4.0+dfsg-3, Dec 20 2014, 13:30:46)
    [PyPy 2.4.0 with GCC 4.9.2] on linux2

With Python 3, the error is different (`TypeError: Type str doesn't support the buffer API`).

**Comment by MaximeCheramy** [comment]
`os.path.join(self.bundle_dir, moddata["file"])` fails because `self.bundle_dir` is a `str` that contains an accent and `moddata["file"]` is a `unicode` string.

**Comment by perkinslr** [comment]
That makes sense, probably makes more sense to convert it to unicode, since that's what python3 uses, but I can't find anything official about what filepaths are supposed to be...

**Comment by rfk** [comment]
I added some basic unicode coercion in https://github.com/rfk/pypyjs/commit/61a217709d6a4c60f75104ad5f92bc0b68fdd1c3; please re-open if the new version still gives errors for you
