### ISSUE TITLE
__name__=='__builtin__'

### ISSUE THREAD

**Issue by perkinslr** [rfk/pypyjs#89]
When running a script via `vm.eval('execfile(somepath)');` blocks protected via `__name__=='__main__'` do not execute.  When you run `vm.eval('print __name__');` the name printed is `__builtin__`.

**Comment by rfk** [comment]
Nice catch; hopefully this will be a simple matter of setting `__name__` explicitly in the global environment of the interpreter.

**Comment by perkinslr** [comment]
I believe that is how it normally works, it is defined inside the globals() dict, rather than a builtin value.  __builtins__.__name__=='__builtin__', so that explains the current value.

**Comment by kirbyfan64** [comment]
@perkinslr Just wrap the special text inside of single backticks.

`__A__` is surrounded by backticks, __A__ isn't.

**Comment by rfk** [comment]
Should be fixed by https://github.com/rfk/pypyjs/commit/3c966e3b049acb4aad516355464d6d6a4f65df49
