### ISSUE TITLE
Push PyPyJS setup to separate file

### ISSUE THREAD

**Issue by perkinslr** [rfk/pypyjs#91]
Currently, the pypy vm is initialized directly in index.html, and all the boiler plate to make it actually run scripts or an REPL is also directly in index.html.  Since exceptions outside of the InteractiveConsole don't give particularly useful tracebacks, there is very little reason to startup without the InteractiveConsole, with input directed to it.  This would make including pypyjs much easier, since the boiler plate turns into something like handler = new PyPyHandler(); handler.execfile('/lib/pypyjs/lib_pypy/somefile.py');  It would take slightly more than that to launch the REPL, since you'd need to provide a stdout and prompt function, but compared to the current implementation it would be much simpler to dive in.

**Comment by rfk** [comment]
> Since exceptions outside of the InteractiveConsole don't give particularly useful tracebacks

FWIW I want to fix this eventually, so that uncaught exceptions turn into proper JS Error instances with useful information in them.  Note sure how to go about it yet, but it's on my list.

I've been meaning to factor out the `InteractiveConsole` stuff into a helper method for a while, and the `execfile` helper is an excellent idea.

**Comment by rfk** [comment]
The latest version now contains `execfile()` and `repl()` methods.  It doesn't help with getting nice error tracebacks from `eval()` but it does clean up a lot of boilerplate in the demo site.

**Comment by rfk** [comment]
As of https://github.com/rfk/pypyjs/commit/7fddfb02c011e2a9bd824bf2cd28d0255d33ce25, any call to `eval()` or `exec()` that raises an error should result in the promise being rejected with a `PyPyJS.Error` instance.  The error should contain the type name, message, and traceback from the python exception to assist in debugging.

Does this combination of changes address what you were after in this issue?

**Comment by perkinslr** [comment]
I think so, and rolling the boiler plate into pypy.js is probably the best solution.
