### ISSUE TITLE
paste code with empty lines will break...

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#99]
e.g.:
copy this:
```
import platform

print(platform.platform())
```
paste in PyPyJS will result in this:
```
>>> import platform 
...  
... print(platform.platform())
debug: OperationError:
debug:  operror-type: SyntaxError
debug:  operror-value: ('EOL while scanning string literal', ('c callback', 1, 12, "r = c.push('import platform\n", 0))
>>> 
```

Split empty lines?!?

**Comment by perkinslr** [comment]
Um, actually the better solution is to make it push the code using ''' or """, which handle multi-line input, which I did on my local copy, but I forgot to make a pull request for it.

**Comment by rfk** [comment]
Should be fixed in https://github.com/rfk/pypyjs/commit/3f71bc9cb2de2e0abb99d5d1ae724ff6e46dc925

For some unknown reason the `'''` solution didn't seem to work properly for me, so I went ahead with splitting it line-by-line.

**Comment by jedie** [comment]
maybe https://github.com/rfk/pypyjs/commit/3f71bc9cb2de2e0abb99d5d1ae724ff6e46dc925 is the reason for https://github.com/rfk/pypyjs/issues/104 ?
